info:
  name: Update OpenSubtitles configuration
  type: http
  seq: 1

http:
  method: PUT
  url: "{{baseUrl}}/settings/opensubtitles"
  body:
    type: json
    data: |-
      {
        "api_key": ""
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
